server:
  port: 8085

spring:
  application:
    name: ms-gateway-service
  config:
    import: optional:configserver:http://root:123456@localhost:7070
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-cliente-service
          uri: lb://ms-cliente-service
          predicates:
            - Path=/clientes/**
          filters:
            - AuthFilter

        - id: ms-venta-service
          uri: lb://ms-venta-service
          predicates:
            - Path=/api/ventas/**
          filters:
            - AuthFilter

        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**

        - id: ms-proveedor2-service
          uri: lb://ms-proveedor2-service
          predicates:
            - Path=/api/proveedores/**
          filters:
            - AuthFilter

        - id: ms-almacen-service
          uri: lb://ms-almacen-service
          predicates:
            - Path=/api/productos-terminados/**, /api/materia_prima/**, /api/almacenes/**, /api/detalle-ingresos/**, /api/ingresos-materia-prima/**, /api/stock-almacen/**
          filters:
            - AuthFilter

        - id: ms-producto-service
          uri: lb://ms-producto-service
          predicates:
            - Path=/api/productos/**

        - id: ms-diseno-service
          uri: lb://ms-diseno-service
          predicates:
            - Path=/api/disenos/**


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
