server:
  port: ${PORT:${SERVER_PORT:0}} # Esto genera un puerto aleatorio al iniciar

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db-productos?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  application:
    name: ms-producto-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true # ✅ Para que se registre con IP y puerto correcto

springdoc:
  swagger-ui:
    path: /doc/swagger-ui.html
  api-docs:
    enabled: true
